parameters:
#    cg_main.example.class: CG\MainBundle\Example

services:
#    cg_main.example:
#        class: %cg_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    cg_main.menu_builder:
        class: CG\MainBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    cg_main.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: cg_main.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    cg_main.admin.news:
        id: cg_main.admin.news
        class: 'CG\MainBundle\Block\NewsBlockService'
        tags:
            - { name: sonata.block }
        arguments: ["NewsBlockService","@templating"]
        calls:
            - [setEntityManager, ["@doctrine.orm.default_entity_manager"]]